# Generated by Django 5.2.9 on 2025-12-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tech_stack', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='creators/')),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('skills_and_interests', models.TextField(blank=True, null=True)),
                ('followers_count', models.IntegerField(default=0)),
            ],
        ),
    ]
