# Generated by Django 5.2.9 on 2025-12-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
