# Generated by Django 5.2.9 on 2025-12-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_creator_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creator',
            name='tech_stack',
            field=models.CharField(max_length=500),
        ),
    ]
